<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>PhotoOrganizer</AssemblyName>
    <RootNamespace>PhotoOrganizer.App</RootNamespace>
    <ApplicationIcon>Assets/photo-organizer-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="System.Management" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
    <ProjectReference Include="../PhotoOrganizer.Core/PhotoOrganizer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PhotoOrganizer.App.Tests" />
  </ItemGroup>
</Project>
